//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulasSiencb2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9F-32-60-80-2C-2E-A3-1C-2F-81-4B-24-2B-64-52-EA-B7-75-31-90-12-8D-1F-EE-69-51-5A-" +
            "B6-42-EB-FF-36")]
        public string PasswordAdmin {
            get {
                return ((string)(this["PasswordAdmin"]));
            }
            set {
                this["PasswordAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT USUARIO_NOMBRE FROM localUsers WHERE USUARIO_NUMERO = @userNumber and USUA" +
            "RIO_CURP = @userCurp ;")]
        public string GetUserQuery {
            get {
                return ((string)(this["GetUserQuery"]));
            }
            set {
                this["GetUserQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO localUsers (USUARIO_NUMERO,USUARIO_CURP,USUARIO_NOMBRE) VALUES (@user" +
            "Number, @userCurp, @name);")]
        public string InsertUserQuery {
            get {
                return ((string)(this["InsertUserQuery"]));
            }
            set {
                this["InsertUserQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.siencb.ipn.mx:5050/")]
        public string UrlServer {
            get {
                return ((string)(this["UrlServer"]));
            }
            set {
                this["UrlServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148.204.160.101")]
        public string ftpServer {
            get {
                return ((string)(this["ftpServer"]));
            }
            set {
                this["ftpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"servicios\":[{\"PK_SERVICIO\":4,\"NOMBRE_SERVICIO\":\"ABIERTO\"},{\"PK_SERVICIO\":1,\"NOM" +
            "BRE_SERVICIO\":\"CLASE\"},{\"PK_SERVICIO\":3,\"NOMBRE_SERVICIO\":\"DIGITALIZACIÓN\"},{\"PK" +
            "_SERVICIO\":2,\"NOMBRE_SERVICIO\":\"IMPRESIÓN\"}],\"paqueteria\":[{\"PK_EQUIPO\":30,\"NOMB" +
            "RE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":2,\"NOMBRE_PROGRAMA\":\"Adobe Dreamweaver CS6" +
            "\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":3,\"NOMBRE_PROGRAMA" +
            "\":\"Adobe Ilustrator CS6\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGR" +
            "AMA\":4,\"NOMBRE_PROGRAMA\":\"Adobe Photoshop CS6\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":" +
            "\"EQUIPO 205\",\"PK_PROGRAMA\":15,\"NOMBRE_PROGRAMA\":\"Chrome\"},{\"PK_EQUIPO\":30,\"NOMBR" +
            "E_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":5,\"NOMBRE_PROGRAMA\":\"CoreDRAW X7\"},{\"PK_EQU" +
            "IPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":14,\"NOMBRE_PROGRAMA\":\"Firefox" +
            "\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":13,\"NOMBRE_PROGRAM" +
            "A\":\"Internet Explorer\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAM" +
            "A\":9,\"NOMBRE_PROGRAMA\":\"Microsoft Access 2019\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":" +
            "\"EQUIPO 205\",\"PK_PROGRAMA\":7,\"NOMBRE_PROGRAMA\":\"Microsoft Excel 2019\"},{\"PK_EQUI" +
            "PO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":8,\"NOMBRE_PROGRAMA\":\"Microsoft" +
            " PowerPoint 2019\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":11" +
            ",\"NOMBRE_PROGRAMA\":\"Microsoft Project 2019\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQ" +
            "UIPO 205\",\"PK_PROGRAMA\":10,\"NOMBRE_PROGRAMA\":\"Microsoft Publisher 2019\"},{\"PK_EQ" +
            "UIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":12,\"NOMBRE_PROGRAMA\":\"Micros" +
            "oft Visio 2019\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 205\",\"PK_PROGRAMA\":6,\"N" +
            "OMBRE_PROGRAMA\":\"Microsoft Word 2019\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":\"EQUIPO 2" +
            "05\",\"PK_PROGRAMA\":16,\"NOMBRE_PROGRAMA\":\"Opera\"},{\"PK_EQUIPO\":30,\"NOMBRE_EQUIPO\":" +
            "\"EQUIPO 205\",\"PK_PROGRAMA\":20,\"NOMBRE_PROGRAMA\":\"Redes sociales\"}]}\r\n")]
        public string UsePC {
            get {
                return ((string)(this["UsePC"]));
            }
            set {
                this["UsePC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://148.204.161.28/api/miembros/foto/get/")]
        public string UrlServerPhotos {
            get {
                return ((string)(this["UrlServerPhotos"]));
            }
            set {
                this["UrlServerPhotos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServicesUDI {
            get {
                return ((string)(this["ServicesUDI"]));
            }
            set {
                this["ServicesUDI"] = value;
            }
        }
    }
}
